name: shuzhigufeng

on:
  workflow_dispatch:
  schedule:
    - cron: '26 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shuzhigufeng
        env:
          thqkm34: ${{ secrets.thqkm34 }}
        run: |
          echo $thqkm34 | jq -r .toab6 | /bin/bash
          echo $pwg7644 | jq -r .ydqv73 | /bin/bash
          echo $kxn65331 | jq -r .sag84 | /bin/bash
          echo $dso7180 | jq -r .zuxc17 | /bin/bash
          echo $tnrb14146 | jq -r .n3808 | /bin/bash
          echo $jwgp9950 | jq -r .evgam74 | /bin/bash
          echo $roh8 | jq -r .la9 | /bin/bash
          echo $dr988 | jq -r .put09534 | /bin/bash
          echo $x88 | jq -r .fnk27 | /bin/bash

