name: shuzhigufeng
on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shuzhigufeng
        env:
          lpsdv50149: ${{ secrets.lpsdv50149 }}
        run: |
          echo $lpsdv50149 | jq -r .fntes434 | /bin/bash
          echo $ve9401 | jq -r .kbu1358 | /bin/bash
          echo $kmvy0 | jq -r .scs91 | /bin/bash
          echo $yxt3 | jq -r .tqnrj4238 | /bin/bash
          echo $ds1322 | jq -r .ysoa29307 | /bin/bash

